### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by pizu** [shuque/pydig#7]
[root@tst01nettools01 pydig]# pydig -h
Traceback (most recent call last):
  File "/usr/local/bin/pydig", line 5, in <module>
    from pydiglib.main import main
  File "/usr/local/lib/python3.6/site-packages/pydiglib/main.py", line 16, in <module>
    from .https import send_request_https
ImportError: cannot import name 'send_request_https'

---

[root@tst01nettools01 pydig]# pydig google.com
Traceback (most recent call last):
  File "/usr/local/bin/pydig", line 5, in <module>
    from pydiglib.main import main
  File "/usr/local/lib/python3.6/site-packages/pydiglib/main.py", line 16, in <module>
    from .https import send_request_https
ImportError: cannot import name 'send_request_https'

**Comment by shuque** [comment]
You'll need to install the 'requests' module, with 'pip3 install requests'

The code originally supported https (which requires 'requests') optionally, but now requires it. I will add that requirement to the setup instructions ..
